### ISSUE TITLE
Cordova run android error: UnhandledPromiseRejectionWarning: Error: spawn EACCES

### ISSUE THREAD

**Issue by sandrhymend** [ionicthemes/ion2fullapp#18]
I removed it.
ionic cordova platform rm android

and I recreated it but I got this error

smendoza$ cordova run android
Discovered plugin "call-number" in config.xml. Adding it to the project
Plugin "mx.ferreyra.callnumber" already installed on android.
ANDROID_HOME=/Users/smendoza/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
(node:78984) UnhandledPromiseRejectionWarning: Error: spawn EACCES
    at _errnoException (util.js:992:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at Object.exports.spawn (/Users/smendoza/Documents/Ionic-Projects/ion2fullapp-elite/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:134:31)
    at GradleBuilder.runGradleWrapper (/Users/smendoza/Documents/Ionic-Projects/ion2fullapp-elite/platforms/android/cordova/lib/builders/GradleBuilder.js:78:27)
    at /Users/smendoza/Documents/Ionic-Projects/ion2fullapp-elite/platforms/android/cordova/lib/builders/GradleBuilder.js:177:21
    at _fulfilled (/Users/smendoza/Documents/Ionic-Projects/ion2fullapp-elite/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/smendoza/Documents/Ionic-Projects/ion2fullapp-elite/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/smendoza/Documents/Ionic-Projects/ion2fullapp-elite/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /Users/smendoza/Documents/Ionic-Projects/ion2fullapp-elite/platforms/android/cordova/node_modules/q/q.js:570:49
(node:78984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:78984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Android Studio 3.1.4

Any help?

**Comment by djabif** [comment]
As suggested in https://github.com/ionicthemes/ion2fullapp/issues/1#issuecomment-385047489 
To solve this issue run:

sudo chmod 777 “/Applications/Android Studio.app/Contents/gradle/gradle-4.1/bin/gradle”
— BE CAREFUL to the gradle version is yours —

**Comment by sandrhymend** [comment]
Same issue
https://github.com/ionic-team/ionic-cli/issues/2835

Command is : sudo chmod -R 777 /Users/YourUserName/Library/Android/Applications/Android\ Studio.app/Contents/gradle/gradle-4.1/bin/gradle

I couldn't find this path /Users/YourUserName/Library/Android/Applications/Android\ Studio.app/Contents/gradle/gradle-4.1/bin/gradle on my computer.

Mac OS Sierra 10.12.16

:(

**Comment by djabif** [comment]
What about this one https://github.com/ionic-team/ionic-cli/issues/2835#issuecomment-340875489 ?
Try to check where do you have installed gradle and update your path with that

**Comment by sandrhymend** [comment]
Found it
echo $GRADLE_HOME
/usr/local/gradle/gradle-4.0.2

sudo chmod -R 777 "/usr/local/gradle/gradle-4.0.2/bin/gradle”

Thank you It's fixed now.
