### ISSUE TITLE
 @ionic/app-scripts 

### ISSUE THREAD

**Issue by andrew1618** [ionicthemes/ion2fullapp#28]
Can't run ionic serve because I get this error:
Looks like @ionic/app-scripts isn't installed in this project
 This package is required for this command to work properly. The package 
       provides a CLI utility, but the ionic-app-scripts binary was not found in 
       your PATH.

? Install @ionic/app-scripts? Yes

I enter YES and then get this:
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.

> fsevents@1.2.7 install /Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and node@10.15.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/lib' 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/root/.node-gyp/10.15.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/.node-gyp'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)

> node-sass@4.7.2 install /Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/node-sass/vendor/darwin-x64-64 : { Error: EACCES: permission denied, mkdir '/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:752:3)
    at sync (/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/node-sass/scripts/install.js:111:11)
    at Object.<anonymous> (/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/node-sass/scripts/install.js:154:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path:
   '/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/node-sass/vendor' }

> node-sass@4.7.2 postinstall /Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import sys; print "2.7.14
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.15.3
gyp verb command install [ '10.15.3' ]
gyp verb install input version string "10.15.3"
gyp verb install installing version: 10.15.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/root/.node-gyp/10.15.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '10.15.3' ]
gyp verb install input version string "10.15.3"
gyp verb install installing version: 10.15.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.15.3
gyp verb ensuring nodedir is created /Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/node-sass/.node-gyp/10.15.3
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.15.3' ]
gyp verb remove using node-gyp dir: /Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.15.3
gyp verb remove removing development files for version: 10.15.3
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.15.3' ]
gyp verb remove using node-gyp dir: /Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.15.3
gyp verb remove removing development files for version: 10.15.3
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/node-sass/.node-gyp'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/admin/Desktop/Programming/ionic/ion2fullapp-elite-1.1.3/node_modules/node-sass
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2019-03-26T22_22_09_229Z-debug.log
[ERROR] An error occurred while running subprocess npm.
        
        npm i -D -E @ionic/app-scripts exited with exit code 1.
        

I expected to see the simulation of the app in browser.

Thanks :)

**Comment by djabif** [comment]
Did you run **npm install** before doing **ionic serve**?

**Comment by chevanielle** [comment]
same issue for me
